name: Pós-Merge

on:
  push:
    branches:
      - master # Executa apenas quando há merge na master

jobs:
  cleanup_merged_branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para deletar branches remotas
    steps:
      - name: Executar Composite Action de limpeza de branches
        uses: ./.github/actions/branch-cleaning
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
