name: Pós-Merge

on:
  push:
    branches:
      - master

jobs:
  cleanup_merged_branches:
    name: Delete Outdated Branches
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Executar Composite Action de limpeza de branches
        uses: ./.github/actions/branch-cleaning
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Feedback da execução
        if: success()
        run: echo "✨ Limpeza de branches concluída. Verifique o log acima para detalhes."
